name: Publish to nuget
on:
  release: 
    types: [created]
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Publish to NuGet On New release
        working-directory: ./dotWork
        run: |
          dotnet pack -c Release --include-source --include-symbols --nologo -o ./packed
          dotnet nuget push "./packed/*" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
